global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Threading;
global using Persistence;
global using AutoMapper;
global using MediatR;
global using Domain;
global using System;