global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using Microsoft.AspNetCore.Mvc;
global using Application.Activities;
global using Application.Core;
global using API.Extensions;
global using Persistence;
global using MediatR;
global using Domain;